Repository djotaku/raspi_garage_alert, pull requests merged in 2020-10, with the labels that each got.

#13 Changed MQTT message to retain
  raspigaragealert/services/mqtt.py
Labels: hacktoberfest, hacktoberfest-approved

#15 Documenation!
  raspigaragealert/docs/Makefile
  raspigaragealert/docs/conf.py
  raspigaragealert/docs/configuration.rst
  raspigaragealert/docs/hardware.rst
  raspigaragealert/docs/index.rst
  raspigaragealert/docs/make.bat
Labels: documentation, hacktoberfest, hacktoberfest-approved

#16 added docs requirements for buildthedocs.io
  raspigaragealert/docs/requirements.txt
Labels: documentation

#17 moved docs folder and edited requirements.txt because it was causing …
  docs/Makefile
  docs/conf.py
  docs/configuration.rst
  docs/hardware.rst
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
  requirements.txt
Labels: documentation

#18 tring to get the other documentation pages to work
  docs/index.rst
Labels: documentation

#19 some documentation fixes
  docs/configuration.rst
  docs/hardware.rst
Labels: documentation

#20 changing highlights to code-blocks
  docs/configuration.rst
Labels: documentation

#21 updated readme and pypi readme
  README.md
  pypi.rst
Labels: documentation

#22 trying to fix readme
  README.md
Labels: documentation

#23 Possible fix to jitter issue
  raspigaragealert/garage_door.py
Labels: hacktoberfest, hacktoberfest-approved
